### ISSUE TITLE
Experiment: Improved (lazier) Rope_mergesort vs earlier one

### ISSUE THREAD

**Issue by matthewhammer** [plum-umd/adapton.ocaml#20]
In addressing Issue #19, I have some further questions to help us better understand granularity control in (rope-based) mergesort:

* The improved version uses more `Art`s, and thus consumes more caching resources.  On the other hand, it produces a lazier output list, especially towards the end of this output.  How does it compare with the prior version empirically?

* How well or not well does `median` work now?  Recall that we can be lazier than the current code, by checking the size of the (unsorted) input rather than the (sorted) output.  This will consume more cache space, since we need to compute `length` for both input and half of the output, rather than just the (full) output.  However, maybe the extra laziness in the output will win out in the end.

**Comment by labichn** [comment]
@kyleheadley, is this issue completed after the OOPSLA push?

**Comment by kyleheadley** [comment]
The issue is unsolved, but now an minor point. We've been using the more optimal 'granularity parameter' 5 or 6, which does not have the issues above.
