### ISSUE TITLE
Clean up repo for the public.  Update README.md

### ISSUE THREAD

**Issue by matthewhammer** [plum-umd/adapton.ocaml#25]
adapton.ocaml is a public repo now.  We want our README file to be accurate and complete, but I'm not sure that it is anymore.  Also, we want the organization and naming of the modules and packages to make sense.  With the exception of "Grifola" and "SpreadTree" (@matthewhammer's fault, I admit), I think that things look pretty good.

Let's keep a few people in mind:

 * First, assume the person reading the document wants to run our experiments to reproduce the data for the tables in the paper.  What steps should they do?  (Ideally, as few as possible).

* Next, some people may want to find the code for the benchmarks in our system, or for the core algorithms behind these benchmarks.  For each of these, which version of what should they look at?

Probably, we should make a table that maps module names in experiments.ml to benchmark names in the paper.  Eventually, they'll find "SpreadTree.ml", which I think we should rename to either Struct0 or StructZero.ml.  The file `Struct.ml` can be the next design iteration of basic data structures (currently it has @kyleheadley's design).

* Finally, another situation is: An ocaml programmer wants to use adapton in their project.  We need to address two sources of questions:
  * How do they build the opam package and load it?  Ideally, this is one make command.
  * How do they program against this package, assuming they have built and opam'd it correctly?

**Comment by labichn** [comment]
Done and done.
