### ISSUE TITLE
Spreadsheet example fails to compile: Signature mismatch

### ISSUE THREAD

**Issue by dcharkes** [plum-umd/adapton.ocaml#31]
I installed adapton through `make install` and tried to compile the spreadsheet example, but I got the following error.
Is there anything that I am missing?

```
$ ocamlc -I ~/.opam/4.02.3/lib/adapton/ spreadsheet.ml

File "spreadsheet.ml", line 56, characters 31-40:
Error: Signature mismatch:
       ...
       Values do not match:
         val equal : t -> t -> Ppx_deriving_runtime.bool
       is not included in
         val equal : t -> t -> bool
```

**Comment by dcharkes** [comment]
`$ ocamlbuild -use-ocamlfind spreadsheet.native` as specified in the makefile does work.

However, this does not help me experimenting with Adapton in the interpreter.

To run in interpreter I tried adding

```
#use "topfind";;
#require "adapton";;
```

to the top of the file.

This makes `module AInt = MakeArt.Of(Name)(Types.Int)` succeed, but the next module now fails:

```
# module SSVal (* : Data.S with type t as below*) =
struct
  type t = Atom of AInt.t
         | Prod of t * t
      [@@deriving eq, ord, show]
  let rec hash seed = function
    | Atom ai      -> AInt.hash seed ai
    | Prod (t, t') -> hash (hash seed t) t'
  let rec sanitize = function
    | Atom ai      -> Atom (AInt.sanitize ai)
    | Prod (t, t') -> Prod (sanitize t, sanitize t')
end

Characters 109-111:
  [@@deriving eq, ord, show]
              ^^
Cannot locate deriver eq
```

What does `ocamlbuild` do that the interpreter does not do?

**Comment by labichn** [comment]
Adapton has one OPAM dependency, `ppx_deriving`, which `ocamlbuild` locates in your local OPAM installation with `ocamlfind` when you pass it the `-use-ocamlfind` flag.

The package `ppx_deriving` allows you to do type-directed function generation, and the code `[@@deriving eq, ord, show]` after the type definition for `t` is an [attribute](http://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec245) interpreted by the  `ppx_deriving` PPX extension to generate an equality function (`equal : t -> t -> bool`), a comparison function (`compare : t -> t -> int`), and two printing functions (`show : t -> string`, `pp : Format.formatter.t -> t -> unit`) automatically.

> What does `ocamlbuild` do that the interpreter does not do?

With the `-use-ocamlfind` flag, `ocamlbuild` is automatically recognizing that the package `ppx_deriving.std` is a dependency per the top-level file [_tags](https://github.com/plum-umd/adapton.ocaml/blob/master/_tags) and loading it to perform code generation. This isn't happening in the toplevel when only `adapton` is required. To get `ppx_deriving` to dynamically invoke its drivers in the toplevel you must `#require "ppx_deriving.std" ;;`, which installs the standard (built-in) deriving plugins, including `eq`, `ord`, and `show`. With this, you should be able to `#use` spreadsheet.ml (as shown below).

Thanks for pointing out a shortcoming in our documentation--I rarely use the toplevel myself and didn't realize it requires an extra step to get our spreadsheet example running.

Running 4.02.3 with ppx_deriving 3.3 (latest available):

```
# #use "topfind" ;;
- : unit = ()
Findlib has been successfully loaded. Additional directives: ...
# #require "adapton" ;; ...
# #use "sample/spreadsheet.ml" ;;
module AInt : ...
File "sample/spreadsheet.ml", line 87, characters 14-16:
Cannot locate deriver eq
# #require "ppx_deriving.std" ;;
ppx_deriving: .../.opam/4.02.3/lib/ppx_deriving/./ppx_deriving_show.cma: option added
ppx_deriving: .../.opam/4.02.3/lib/ppx_deriving/./ppx_deriving_eq.cma: option added
ppx_deriving: .../.opam/4.02.3/lib/ppx_deriving/./ppx_deriving_ord.cma: option added
...
# #use "sample/spreadsheet.ml" ;;
module AInt : ...
module SSVal : ...
val eval : SSVal.t -> AInt.t = <fun>
val mutate : SSVal.t -> int -> unit = <fun>
val print : AInt.t -> unit = <fun>
val nm : int -> Adapton.Name.t = <fun>
val cell : int -> AInt.t = <fun>
val test : (SSVal.t -> AInt.t) -> unit = <fun>
Running eval test.
The spreadsheet entry's value is 24.
Mutating one of the entries!
The spreadsheet entry's value is 30.
- : unit = ()
val print_eval : SSVal.t -> AInt.t = <fun>
Running eval test.
  eval 4
  eval 2
  eval 3
  eval 2 * 3
  eval 4 * 6
The spreadsheet entry's value is 24.
Mutating one of the entries!
  eval 5
  eval 5 * 6
The spreadsheet entry's value is 30.
- : unit = ()
```

**Comment by dcharkes** [comment]
```
#use "topfind";;
#require "adapton";;
#require "ppx_deriving.std";;
```

does the trick.

I figured this out by looking at the verbose ocamlbuild output:

```
$ ocamlbuild -use-ocamlfind spreadsheet.native -verbose 1
include directories are: [ "." ]
cache miss: a product is not in build dir (spreadsheet.ml.depends)
ocamlfind ocamldep -package 'adapton, ppx_deriving.std' -modules spreadsheet.ml > spreadsheet.ml.depends
...
```

Generic OCaml question: Is there a way to automate `#require`s in the interpreter?

Issue can be closed.

**Comment by dcharkes** [comment]
@labichn thanks for your explanation!
