### ISSUE TITLE
create an oo interface to encapsulate data types

### ISSUE THREAD

**Issue by kyleheadley** [plum-umd/adapton.ocaml#4]
The issue is that Adapton needs metadata for all its datatypes. Keeping track of it takes extra lines of code that are otherwise mechanical to produce.

The suggestion is to use objects to encapsulate both the data and its type. Care will need to be taken to make sure that objects share namespaces and memo tables appropriately. 

First step is to create a wrapper for existing code. We can use the knowledge of working with that to assist in optimizing the main code for ease of use.

See Notes.txt in the root directory for an extended discussion. An excerpt:
    class 'a IResult:
      n#get():'a                      forces computation
      n#try(val:'a):()               will ignore computation and pass val to dependents 
      n#reset():()                    returns computation to default
      n#type():DatType with t = 'a    gets the type module

**Comment by labichn** [comment]
I'd rather solve the module passing problem with ppx_implicit.
