### ISSUE TITLE
Make sure the logging functionality is working

### ISSUE THREAD

**Issue by kyleheadley** [plum-umd/adapton.ocaml#8]
Activate the log functionality. Minimally, this will involve adding a makefile entry to compile the experiments file with logging enabled.

We will have to decide whether or not we are keeping camlp4, which was the original system used to compiler with or without the logging. Probably keep it for now to get things working

**Comment by kyleheadley** [comment]
A temporary fix was implemented and discussed in issue #23. We should find a way to include Spreadtree.ml, which must currently be recompiled with the adapton_core_logging to be used.

We want users to setup Adapton in opam once and have access to all features without resetting it.

**Comment by labichn** [comment]
The in-depth logging has been excised until we can find a more elegant solution (not involving camlp4).
